const crops = [
  {
    id: '1',
    name: 'Tomato',
    icon: require('@/assets/images/crops/tomato.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '18-24 in',
    depth: '¼ in',
    water: '1',
    season: 'Wet/Dry',
    germination: '6-8 days',
    sproutToHarvest: '60-85 days',
    pests: [
      {
        name: 'Aphids',
        image: require('@/assets/images/pests/aphid.jpg'),
        description:
          'Aphids are small sap-sucking insects and members of the superfamily Aphidoidea. Common names include greenfly and blackfly, although individuals within a species can vary widely in color. The group includes the fluffy white woolly aphids.',
      },
      { name: 'Cutworms', image: require('@/assets/images/pests/cutworm.jpg') },
      {
        name: 'Corn earworm',
        image: require('@/assets/images/pests/corn-earworm.jpg'),
      },
      {
        name: 'Flea beetles',
        image: require('@/assets/images/pests/flea-beetles.jpg'),
      },
      {
        name: 'Brown Marmorated Stink Bug',
        image: require('@/assets/images/pests/brown-marmorated-stink-bug.jpg'),
      },
      { name: 'Slug', image: require('@/assets/images/pests/slug.png') },
      {
        name: 'Tarnished plant bug',
        image: require('@/assets/images/pests/tarnished-plant-bug.jpg'),
      },
      {
        name: 'Nematode',
        image: require('@/assets/images/pests/nematode.jpg'),
      },
      {
        name: 'Agromyzidae',
        image: require('@/assets/images/pests/agromyzidae.jpg'),
      },
      {
        name: 'Five-spotted hawk moth',
        image: require('@/assets/images/pests/five-spotted-hawk-moth.jpg'),
      },
      {
        name: 'Thrips',
        image: require('@/assets/images/pests/thrips.jpeg'),
      },
      {
        name: 'Tomato leafminer',
        image: require('@/assets/images/pests/tomato-leafminer.jpg'),
      },
      {
        name: 'Spider Mites',
        image: require('@/assets/images/pests/spider-mites.jpg'),
      },
      {
        name: 'Hornworms',
        image: require('@/assets/images/pests/hornworms.jpg'),
      },
      {
        name: 'Whiteflies',
        image: require('@/assets/images/pests/whiteflies.jpg'),
      },
      {
        name: 'Colorado potato beetle',
        image: require('@/assets/images/pests/colorado-potato-beetle.jpg'),
      },
      {
        name: 'Caterpillars',
        image: require('@/assets/images/pests/caterpillars.jpg'),
      },
    ],
    diseases: [
      {
        name: 'Alternaria solani',
        image: require('@/assets/images/diseases/alternaria-solani.jpg'),
        description:
          'Alternaria solani is a fungal pathogen that produces a disease in tomato and potato plants called early blight.',
      },
      {
        name: 'Calcium deficiency',
        image: require('@/assets/images/diseases/calcium-deficiency.jpg'),
      },
      {
        name: 'Bacterial spot',
        image: require('@/assets/images/diseases/bacterial-spot.jpg'),
      },
      {
        name: 'Botrytis cinerea',
        image: require('@/assets/images/diseases/botrytis-cinerea.jpg'),
      },
      {
        name: 'Catfacing',
        image: require('@/assets/images/diseases/catfacing.jpg'),
      },
    ],
  },
  {
    id: '2',
    name: 'Bitter Gourd',
    icon: require('@/assets/images/crops/bitter-gourd.png'),
    description:
      'Bitter Gourd is a climbing vine, nearly or quite smooth, annual vine. Tendrils are simple, up to 20 centimeters long. Leaves are 2.5 to 10 centimeters in diameter, cut nearly to the base into 5 to 7 lobes, oblong-ovate, variously toothed, and heart shaped at the base.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '1.5-2.5 m',
    depth: '½ in',
    water: '1',
    season: 'Wet/Dry',
    germination: '8-10 days',
    sproutToHarvest: '55-60 days',
  },
  {
    id: '3',
    name: 'Pumpkin',
    icon: require('@/assets/images/crops/pumpkin.png'),
    description:
      'Pumpkin is a course, prostrate or climbing, annual, herbaceous vine, reaching a length of 4 meters or more. Leaves are hispid, rounded, 15 to 30 centimeters in diameter, heart-shaped at the base, shallowly 5-lobed, with finely toothed margins, and often mottled on the upper surface.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '36-60 in',
    depth: '1-2 in',
    water: '1',
    season: 'Wet/Dry',
    germination: '10 days',
    sproutToHarvest: '90-120 days',
  },
  {
    id: '4',
    name: 'Lady’s Finger',
    icon: require('@/assets/images/crops/ladys-finger.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '14-16 in',
    depth: '1 in',
    water: '2',
    season: 'Dry',
    germination: '6-8 days',
    sproutToHarvest: '60-70 days',
  },
  {
    id: '5',
    name: 'Lettuce',
    icon: require('@/assets/images/crops/lettuce.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '6-18 in',
    depth: '¼-½ in',
    water: '2',
    season: 'Wet/Dry',
    germination: '7-10 days',
    sproutToHarvest: '30-70 days',
  },
  {
    id: '6',
    name: 'Cucumber',
    icon: require('@/assets/images/crops/cucumber.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '12 in',
    depth: '1 in',
    water: '1',
    season: 'Dry',
    germination: '3-10 days',
    sproutToHarvest: '50-70 days',
  },
  {
    id: '7',
    name: 'Moringa',
    icon: require('@/assets/images/crops/moringa.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '3 m',
    depth: '1 in',
    water: '1-2',
    season: 'Dry',
    germination: '7-30 days',
    sproutToHarvest: '42-56 days',
  },
  {
    id: '8',
    name: 'String Bean',
    icon: require('@/assets/images/crops/string-bean.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '1 m',
    depth: '2-3 cm',
    water: '1-2',
    season: 'Dry',
    germination: '4-10 days',
    sproutToHarvest: '50-55 days',
  },
  {
    id: '9',
    name: 'Chinese Cabbage',
    icon: require('@/assets/images/crops/chinese-cabbage.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '12-18 in',
    depth: '¼-½ in',
    water: '1',
    season: 'Wet/Dry',
    germination: '7-14 days',
    sproutToHarvest: '40-100 days',
  },
  {
    id: '10',
    name: 'Mustard Green',
    icon: require('@/assets/images/crops/mustard-green.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '12-18 in',
    depth: '½ in',
    water: '1-2',
    season: 'Wet/Dry',
    germination: '7-10 days',
    sproutToHarvest: '42 days',
  },
  {
    id: '11',
    name: 'Chilli',
    icon: require('@/assets/images/crops/chilli.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '15-18 in',
    depth: '¼ in',
    water: '2',
    season: 'Wet/Dry',
    germination: '10-14 days',
    sproutToHarvest: '60-100 days',
  },
  {
    id: '12',
    name: 'Long Squash',
    icon: require('@/assets/images/crops/long-squash.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '24-30 in',
    depth: '1-½ in',
    water: '1',
    season: 'Dry',
    germination: '7-10 days',
    sproutToHarvest: '60-110 days',
  },
  {
    id: '13',
    name: 'Lima Bean',
    icon: require('@/assets/images/crops/lima-bean.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '2-4 in',
    depth: '1/2 in',
    water: '1',
    season: 'Wet/Dry',
    germination: '7-18 days',
    sproutToHarvest: '60-90 days',
  },
  {
    id: '14',
    name: 'Winged Bean',
    icon: require('@/assets/images/crops/winged-bean.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '4 in',
    depth: '1 in',
    water: '2',
    season: 'Dry',
    germination: '7-21 days',
    sproutToHarvest: '120-240 days',
  },
  {
    id: '15',
    name: 'Silk Squash',
    icon: require('@/assets/images/crops/silk-squash.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '6-8 in',
    depth: '12 in',
    water: '1',
    season: 'Wet/Dry',
    germination: '7-10 days',
    sproutToHarvest: '60-70 days',
  },
  {
    id: '16',
    name: 'Chayote',
    icon: require('@/assets/images/crops/chayote.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '6-8 feet',
    depth: '3-5 in',
    water: '3-4',
    season: 'Wet/Dry',
    germination: '21-28 days',
    sproutToHarvest: '121-182 days',
  },
  {
    id: '17',
    name: 'Eggplant',
    icon: require('@/assets/images/crops/eggplant.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '18-24 in',
    depth: '1-4 in',
    water: '1-2',
    season: 'Wet/Dry',
    germination: '7-14 days',
    sproutToHarvest: '70 days',
  },
  {
    id: '18',
    name: 'Water Spinach',
    icon: require('@/assets/images/crops/water-spinach.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '20-30 cm',
    depth: '1 cm',
    water: '2',
    season: 'Wet',
    germination: '7-14 days',
    sproutToHarvest: '50-60 days',
  },
  {
    id: ' 19',
    name: 'Spinach',
    icon: require('@/assets/images/crops/spinach.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '3 in',
    depth: '½ in',
    water: '1-2',
    season: 'Wet',
    germination: '5 days',
    sproutToHarvest: '45-50 days',
  },
  {
    id: '20',
    name: 'Black Pepper',
    icon: require('@/assets/images/crops/black-pepper.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Vegetables',
    isFavorite: false,
    spacing: '18 in',
    depth: '2-3 in',
    water: '3',
    season: 'Wet',
    germination: '5-20 days',
    sproutToHarvest: '730-1095 days',
  },
  {
    id: '21',
    name: 'Papaya',
    icon: require('@/assets/images/crops/tomato.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '1.5 m',
    depth: '1 m',
    water: '1',
    season: 'Dry',
    germination: '7-14 days',
    sproutToHarvest: '182-212 days',
  },
  {
    id: '22',
    name: 'Philippine Lime',
    icon: require('@/assets/images/crops/philippine-lime.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '5 m',
    depth: '7 cm',
    water: '1',
    season: 'Perennial',
    germination: '21-42 days',
    sproutToHarvest: '365-730 days',
  },
  {
    id: '23',
    name: 'Banana',
    icon: require('@/assets/images/crops/banana.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '2 m',
    depth: '60-80 cm',
    water: '1',
    season: 'Perennial',
    germination: '14 days',
    sproutToHarvest: '334-425 days',
  },
  {
    id: '24',
    name: 'Mango',
    icon: require('@/assets/images/crops/mango.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '15 m',
    depth: '1/2 in',
    water: '1',
    season: 'Perennial',
    germination: '7-21 days',
    sproutToHarvest: '1825-2920 days',
  },
  {
    id: '25',
    name: 'Guava',
    icon: require('@/assets/images/crops/guava.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '6.5m',
    depth: '1 m',
    water: '1',
    season: 'Perennial',
    germination: '21 days',
    sproutToHarvest: '1095-2920 days',
  },
  {
    id: '26',
    name: 'Pineapple',
    icon: require('@/assets/images/crops/pineapple.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '80-100 cm',
    depth: '3-4 in',
    water: '2',
    season: 'Perennial',
    germination: '182-365 days',
    sproutToHarvest: '547-1095 days',
  },
  {
    id: '27',
    name: 'Avocado',
    icon: require('@/assets/images/crops/avocado.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '8 m',
    depth: '12-18 in',
    water: '1',
    season: 'Perennial',
    germination: '42-56 days',
    sproutToHarvest: '730 days',
  },
  {
    id: '28',
    name: 'Pomelo',
    icon: require('@/assets/images/crops/pomelo.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '10 m',
    depth: '0.5 in',
    water: '1',
    season: 'Perennial',
    germination: '14-56 days',
    sproutToHarvest: '2920 days',
  },
  {
    id: '29',
    name: 'Coconut',
    icon: require('@/assets/images/crops/coconut.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '7.5-8.5 m',
    depth: '60-90 cm',
    water: '1',
    season: 'Perennial',
    germination: '121 days',
    sproutToHarvest: '1095-2920 days',
  },
  {
    id: '30',
    name: 'Passion Fruit',
    icon: require('@/assets/images/crops/passion-fruit.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '1.2-2.5 m',
    depth: '8 mm',
    water: '1',
    season: 'Perennial',
    germination: '21-84 days',
    sproutToHarvest: '365-547 days',
  },
  {
    id: '31',
    name: 'Soursop',
    icon: require('@/assets/images/crops/soursop.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '4m-7m',
    depth: '½ in',
    water: '1',
    season: 'Perennial',
    germination: '15-30 days',
    sproutToHarvest: '1095-1825 days',
  },
  {
    id: '32',
    name: 'Cotton Fruit',
    icon: require('@/assets/images/crops/cotton-fruit.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '30-40 in',
    depth: '8 in',
    water: '1',
    season: 'Perennial',
    germination: '5-10 days',
    sproutToHarvest: '1825-2555 days',
  },
  {
    id: '33',
    name: 'Jave Plum',
    icon: require('@/assets/images/crops/jave-plum.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '3-4 in',
    depth: '2 cm',
    water: '1',
    season: 'Perennial',
    germination: '75-90 days',
    sproutToHarvest: '2920-3650 days',
  },
  {
    id: '34',
    name: 'Custard Apple',
    icon: require('@/assets/images/crops/custard-apple.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '5 m',
    depth: '3 cm',
    water: '1',
    season: 'Perennial',
    germination: '55-60 days',
    sproutToHarvest: '243-456 days',
  },
  {
    id: '35',
    name: 'Star Apple',
    icon: require('@/assets/images/crops/star-apple.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '7.6 m',
    depth: '7 in',
    water: '2-3',
    season: 'Perennial',
    germination: '14-21 days',
    sproutToHarvest: '1825-3650 days',
  },
  {
    id: '36',
    name: 'Velvet Apple',
    icon: require('@/assets/images/crops/tomato.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '5-10 m',
    depth: '2-3 cm',
    water: '1-2',
    season: 'Perennial',
    germination: '14-21 days',
    sproutToHarvest: '1095-1825 days',
  },
  {
    id: '37',
    name: 'Cucumber Tree',
    icon: require('@/assets/images/crops/tomato.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '30cm-60cm',
    depth: '1 in',
    water: '1',
    season: 'Perennial',
    germination: '90 days',
    sproutToHarvest: '365-1825 days',
  },
  {
    id: '38',
    name: 'Spanish Plum',
    icon: require('@/assets/images/crops/tomato.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '15-20 in',
    depth: '2 in',
    water: '2',
    season: 'Perennial',
    germination: '70-84 days',
    sproutToHarvest: '1460-1825 days',
  },
  {
    id: '39',
    name: 'Taramind',
    icon: require('@/assets/images/crops/taramind.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '8-10 m',
    depth: '2-3 in',
    water: '1',
    season: 'Perennial',
    germination: '11 days',
    sproutToHarvest: '4745-5110 days',
  },
  {
    id: '40',
    name: 'Sweet Taramind',
    icon: require('@/assets/images/crops/tomato.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Fruits',
    isFavorite: false,
    spacing: '6-9 m',
    depth: '2 cm',
    water: '1',
    season: 'Perennial',
    germination: '14-21 days',
    sproutToHarvest: '1460-2190 days',
  },
  {
    id: '41',
    name: 'Basil',
    icon: require('@/assets/images/crops/basil.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Herbs',
    isFavorite: false,
    spacing: '12-16 in',
    depth: '¼ in',
    water: '1',
    season: 'Dry',
    germination: '7-10 days',
    sproutToHarvest: '60-70 days',
  },
  {
    id: '42',
    name: 'Mint',
    icon: require('@/assets/images/crops/mint.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Herbs',
    isFavorite: false,
    spacing: '18-24 in',
    depth: '¼ in',
    water: '1',
    season: 'Wet/Dry',
    germination: '2-4 days',
    sproutToHarvest: '10-14 days',
  },
  {
    id: '43',
    name: 'Oregano',
    icon: require('@/assets/images/crops/oregano.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Herbs',
    isFavorite: false,
    spacing: '8-10 in',
    depth: '¼ in',
    water: '1',
    season: 'Perennial',
    germination: '10-15 days',
    sproutToHarvest: '80-90 days',
  },
  {
    id: '44',
    name: 'Lemongrass',
    icon: require('@/assets/images/crops/lemongrass.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Herbs',
    isFavorite: false,
    spacing: '24 in',
    depth: '¼ in',
    water: '1',
    season: 'Perennial',
    germination: '7-14 days',
    sproutToHarvest: '5-21 days',
  },
  {
    id: '45',
    name: 'Screw Pine',
    icon: require('@/assets/images/crops/screw-pine.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Herbs',
    isFavorite: false,
    spacing: '5-15 in',
    depth: '1-2 in',
    water: '1',
    season: 'Perennial',
    germination: '60-90 days',
    sproutToHarvest: '121-182 days',
  },
  {
    id: '46',
    name: 'Turmeric',
    icon: require('@/assets/images/crops/turmeric.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Herbs',
    isFavorite: false,
    spacing: '6-8 in',
    depth: '8-12 cm',
    water: '1',
    season: 'Wet/Dry',
    germination: '20 days',
    sproutToHarvest: '182-304 days',
  },
  {
    id: '47',
    name: 'Coriander',
    icon: require('@/assets/images/crops/coriander.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Herbs',
    isFavorite: false,
    spacing: '8-10 in',
    depth: '½ in',
    water: '1',
    season: 'Wet/Dry',
    germination: '7-21 days',
    sproutToHarvest: '28 days',
  },
  {
    id: '48',
    name: 'Parsley',
    icon: require('@/assets/images/crops/parsley.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Herbs',
    isFavorite: false,
    spacing: '6-8 in',
    depth: '½ in',
    water: '2-3',
    season: 'Dry',
    germination: '10-28 days',
    sproutToHarvest: '260-70 days',
  },
  {
    id: '49',
    name: 'Rosemary',
    icon: require('@/assets/images/crops/rosemary.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Herbs',
    isFavorite: false,
    spacing: '2-3 in',
    depth: '½ in',
    water: '1',
    season: 'Dry',
    germination: '7-14 days',
    sproutToHarvest: '14-28 days',
  },
  {
    id: '50',
    name: 'Aloe Vera',
    icon: require('@/assets/images/crops/aloe-vera.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Herbs',
    isFavorite: false,
    spacing: '24-36 in',
    depth: '½ in',
    water: '2',
    season: 'Perennial',
    germination: '14-42 days',
    sproutToHarvest: '182-212 days',
  },
  {
    id: '51',
    name: 'Sweet Potato',
    icon: require('@/assets/images/crops/sweet-potato.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Root Crops',
    isFavorite: false,
    spacing: '12-18 in',
    depth: '7 cm',
    water: '2',
    season: 'Wet/Dry',
    germination: '40-60 days',
    sproutToHarvest: '85-120 days',
  },
  {
    id: '52',
    name: 'Potato',
    icon: require('@/assets/images/crops/potato.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Root Crops',
    isFavorite: false,
    spacing: '8-12 in',
    depth: '3-5 in',
    water: '1',
    season: 'Wet/Dry',
    germination: '15-30 days',
    sproutToHarvest: '75-90 days',
  },
  {
    id: '53',
    name: 'Taro',
    icon: require('@/assets/images/crops/taro.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Root Crops',
    isFavorite: false,
    spacing: '1 m',
    depth: '6 in',
    water: '1',
    season: 'Wet',
    germination: '7 days',
    sproutToHarvest: '212-365 days',
  },
  {
    id: '54',
    name: 'Purple yam',
    icon: require('@/assets/images/crops/purple-yam.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Root Crops',
    isFavorite: false,
    spacing: '7 m',
    depth: '4 in',
    water: '1',
    season: 'Dry',
    germination: '84 days',
    sproutToHarvest: '180-240 days',
  },
  {
    id: '55',
    name: 'Carrot',
    icon: require('@/assets/images/crops/carrot.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Root Crops',
    isFavorite: false,
    spacing: '2-3 in',
    depth: '¼-½ in',
    water: '2',
    season: 'Dry',
    germination: '14-21 days',
    sproutToHarvest: '14-21 days',
  },
  {
    id: '56',
    name: 'Garlic',
    icon: require('@/assets/images/crops/garlic.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Root Crops',
    isFavorite: false,
    spacing: '6 in',
    depth: '1-2 in',
    water: '1',
    season: 'Dry',
    germination: '7-14 days',
    sproutToHarvest: '273 days',
  },
  {
    id: '57',
    name: 'Onion',
    icon: require('@/assets/images/crops/onion.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Root Crops',
    isFavorite: false,
    spacing: '2-4 in',
    depth: '2 cm',
    water: '1',
    season: 'Dry',
    germination: '7-10 days',
    sproutToHarvest: '60-80 days',
  },
  {
    id: '58',
    name: 'Radish',
    icon: require('@/assets/images/crops/tomato.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Root Crops',
    isFavorite: false,
    spacing: '1-3 in',
    depth: '1 in',
    water: '1',
    season: 'Dry',
    germination: '3-5 days',
    sproutToHarvest: '21-35 days',
  },
  {
    id: '59',
    name: 'Singkamas',
    icon: require('@/assets/images/crops/tomato.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Root Crops',
    isFavorite: false,
    spacing: '8-12 in',
    depth: '1/4 in',
    water: '1',
    season: 'Dry',
    germination: '7-21 days',
    sproutToHarvest: '152-273 days',
  },
  {
    id: '60',
    name: 'Ginger',
    icon: require('@/assets/images/crops/tomato.png'),
    description:
      'The tomato plant, with soft, hairy stems, can grow up to 9 feet tall, has 5-9 leaflets, 4-24 inches long leaves, and small yellow flowers with five pointed lobes on the corolla.',
    category: 'Root Crops',
    isFavorite: false,
    spacing: '1 in',
    depth: '5-10 cm',
    water: '1',
    season: 'Wet/Dry',
    germination: '42-56 days',
    sproutToHarvest: '304-365 days',
  },
];

export default crops;
